package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoodsStock<M extends BaseGoodsStock<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setGoodsNum(java.lang.String goodsNum) {
		set("goodsNum", goodsNum);
	}

	public java.lang.String getGoodsNum() {
		return get("goodsNum");
	}

	public void setGoodsName(java.lang.String goodsName) {
		set("goodsName", goodsName);
	}

	public java.lang.String getGoodsName() {
		return get("goodsName");
	}

	public void setGoodsStandard(java.lang.String goodsStandard) {
		set("goodsStandard", goodsStandard);
	}

	public java.lang.String getGoodsStandard() {
		return get("goodsStandard");
	}

	public void setGoodsCategory(java.lang.String goodsCategory) {
		set("goodsCategory", goodsCategory);
	}

	public java.lang.String getGoodsCategory() {
		return get("goodsCategory");
	}

	public void setGoodsPrice(java.lang.Double goodsPrice) {
		set("goodsPrice", goodsPrice);
	}

	public java.lang.Double getGoodsPrice() {
		return get("goodsPrice");
	}

	public void setGoodsDesc(java.lang.String goodsDesc) {
		set("goodsDesc", goodsDesc);
	}

	public java.lang.String getGoodsDesc() {
		return get("goodsDesc");
	}

	public void setStockWareName(java.lang.String stockWareName) {
		set("stockWareName", stockWareName);
	}

	public java.lang.String getStockWareName() {
		return get("stockWareName");
	}

	public void setStockShelfName(java.lang.String stockShelfName) {
		set("stockShelfName", stockShelfName);
	}

	public java.lang.String getStockShelfName() {
		return get("stockShelfName");
	}

	public void setStockCount(java.lang.Integer stockCount) {
		set("stockCount", stockCount);
	}

	public java.lang.Integer getStockCount() {
		return get("stockCount");
	}

	public void setLastStockInTime(java.lang.String lastStockInTime) {
		set("lastStockInTime", lastStockInTime);
	}

	public java.lang.String getLastStockInTime() {
		return get("lastStockInTime");
	}

	public void setLastStockInUser(java.lang.String lastStockInUser) {
		set("lastStockInUser", lastStockInUser);
	}

	public java.lang.String getLastStockInUser() {
		return get("lastStockInUser");
	}

	public void setLastStockInCount(java.lang.Integer lastStockInCount) {
		set("lastStockInCount", lastStockInCount);
	}

	public java.lang.Integer getLastStockInCount() {
		return get("lastStockInCount");
	}

	public void setLastStockOutTime(java.lang.String lastStockOutTime) {
		set("lastStockOutTime", lastStockOutTime);
	}

	public java.lang.String getLastStockOutTime() {
		return get("lastStockOutTime");
	}

	public void setLastStockOutUser(java.lang.String lastStockOutUser) {
		set("lastStockOutUser", lastStockOutUser);
	}

	public java.lang.String getLastStockOutUser() {
		return get("lastStockOutUser");
	}

	public void setLastStockOutCount(java.lang.Integer lastStockOutCount) {
		set("lastStockOutCount", lastStockOutCount);
	}

	public java.lang.Integer getLastStockOutCount() {
		return get("lastStockOutCount");
	}

}
