package com.demo.common.model;

import com.demo.common.model.base.BaseGoodsStock;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsStock extends BaseGoodsStock<GoodsStock> {
	public static final GoodsStock dao = new GoodsStock();
	
	public Page<GoodsStock> paginate(int pageNumber, int pageSize) {
        return paginate(pageNumber, pageSize, "select *", "from goods_stock order by id asc");
    }
}
